// AUTO-GENERATED by scripts/build-tokens.ts from tokens.json — do not edit by hand.
// Source of truth: Figma, synced via Tokens Studio. Edit tokens.json (or Figma) instead.

export const colors = {
  content: {
    error: {
      default: '#eb2032',
    },
    warn: {
      default: '#efbb00',
    },
    success: {
      default: '#a5d911',
    },
    neutral: {
      default: '#424344',
      subtle: '#6f7274',
      subtlest: '#9da0a3',
      disabled: '#b1b3b5',
      inverse: '#f5f6f6',
    },
    primary: {
      subtlest: '#8dd7fb',
      subtle: '#0d5980',
      disabled: '#b2e4fd',
      default: '#1f2c33',
      inverse: '#e6f6fe',
    },
  },
  surface: {
    neutral: {
      default: '#ffffff',
      subtle: '#f5f6f6',
      disabled: '#e1e2e2',
    },
    primary: {
      disabled: '#e6f6fe',
      active: '#0d5980',
      default: '#8dd7fb',
    },
    error: {
      default: '#fde9eb',
    },
    warn: {
      default: '#fdf8e6',
    },
    success: {
      default: '#f6fbe7',
    },
  },
  border: {
    neutral: {
      bold: '#b1b3b5',
      subtle: '#e1e2e2',
      default: '#d2d3d5',
    },
    primary: {
      bold: '#0b94d9',
      subtle: '#b2e4fd',
      default: '#5ac4fa',
    },
    error: {
      default: '#d61d2e',
    },
    warn: {
      default: '#d9aa00',
    },
    success: {
      default: '#96c50f',
    },
  },
} as const

export const typography = {
  fontFamily: 'Pretendard',
  title1Bold: {
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 32,
    letterSpacing: 0.22,
  },
  title2Bold: {
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 25,
    letterSpacing: -0.45,
  },
  title3Regular: {
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 23,
    letterSpacing: -0.44,
  },
  title3Emphasized: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 23,
    letterSpacing: -0.44,
  },
  headlineRegular: {
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.23,
  },
  headlineEmphasized: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: -0.23,
  },
  bodyRegular: {
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: -0.23,
  },
  bodyEmphasized: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
    letterSpacing: -0.23,
  },
  calloutRegular: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 19,
    letterSpacing: -0.15,
  },
  calloutEmphasized: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 19,
    letterSpacing: -0.15,
  },
  subheadlineRegular: {
    fontSize: 13,
    fontWeight: '400',
    lineHeight: 18,
    letterSpacing: -0.08,
  },
  subheadlineEmphasized: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    letterSpacing: -0.08,
  },
  footnoteRegular: {
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 16,
    letterSpacing: 0,
  },
  footnoteEmphasized: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
    letterSpacing: 0,
  },
} as const

export const spacing = {
  0: 0,
  50: 2,
  100: 4,
  150: 6,
  200: 8,
  300: 12,
  400: 16,
  500: 20,
  600: 24,
  800: 32,
  900: 36,
  1200: 48,
  1600: 64,
  2400: 96,
  4000: 160,
  negative300: -12,
  negative600: -24,
  negative400: -16,
  negative100: -4,
  negative200: -8,
} as const

export const radius = {
  7: 7,
  10: 10,
  16: 16,
  23: 23,
  26: 26,
  30: 30,
  34: 34,
  '4.6': 4.6,
  full: 1000,
} as const

export const stroke = {
  default: 1,
  focusRing: 2,
  hairline: 0.5,
} as const

export const icon = {
  xlarge: 40,
  medium: 24,
  large: 32,
  xsmall: 16,
  small: 20,
} as const
