// Parses tokens.json (DTCG format, synced from Figma via Tokens Studio) and
// generates src/tokens.ts. Run via `pnpm --filter @repo/tokens build:tokens`.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as prettier from 'prettier'

interface DtcgLeaf {
  $type: string
  $value: unknown
}

type DtcgNode = DtcgLeaf | { [key: string]: DtcgNode }

const __dirname = dirname(fileURLToPath(import.meta.url))
const PACKAGE_ROOT = resolve(__dirname, '..')
const SOURCE_PATH = resolve(PACKAGE_ROOT, 'tokens.json')
const OUTPUT_PATH = resolve(PACKAGE_ROOT, 'src/tokens.ts')

function isLeaf(node: DtcgNode): node is DtcgLeaf {
  return typeof node === 'object' && node !== null && '$value' in node
}

// DTCG dimension values are px strings (e.g. "8px", "-4px", "4.6px"); RN/StyleSheet
// consumers want unitless numbers.
function parseDimension(value: unknown): number {
  if (typeof value !== 'string') {
    throw new Error(`Expected a dimension string, got ${JSON.stringify(value)}`)
  }
  const match = /^(-?[\d.]+)px$/.exec(value.trim())
  if (!match) {
    throw new Error(`Unsupported dimension value: "${value}" (expected e.g. "8px")`)
  }
  return Number(match[1])
}

// lineHeight may come out of Figma as an absolute px value or a percentage of
// the type's fontSize — normalize both to a px number.
function parseLineHeight(value: unknown, fontSizePx: number): number {
  if (typeof value !== 'string') {
    throw new Error(`Expected a lineHeight string, got ${JSON.stringify(value)}`)
  }
  const trimmed = value.trim()
  if (trimmed.endsWith('%')) {
    const percent = Number(trimmed.slice(0, -1))
    return Math.round((fontSizePx * percent) / 100)
  }
  return parseDimension(trimmed)
}

function convertTypography(value: unknown): Record<string, unknown> {
  if (typeof value !== 'object' || value === null) {
    throw new Error(`Expected a typography value object, got ${JSON.stringify(value)}`)
  }
  const composite = value as Record<string, unknown>
  const fontSize = parseDimension(composite.fontSize)
  return {
    fontSize,
    fontWeight: String(composite.fontWeight),
    lineHeight: parseLineHeight(composite.lineHeight, fontSize),
    letterSpacing: parseDimension(composite.letterSpacing),
  }
}

function convertLeaf(leaf: DtcgLeaf): unknown {
  switch (leaf.$type) {
    case 'color':
      if (typeof leaf.$value !== 'string') {
        throw new Error(`Unsupported color value: ${JSON.stringify(leaf.$value)}`)
      }
      return leaf.$value
    case 'dimension':
      return parseDimension(leaf.$value)
    case 'fontFamily':
      return leaf.$value
    case 'typography':
      return convertTypography(leaf.$value)
    default:
      throw new Error(`Unsupported token $type: "${leaf.$type}"`)
  }
}

function convertNode(node: DtcgNode): unknown {
  if (isLeaf(node)) return convertLeaf(node)
  const result: Record<string, unknown> = {}
  for (const [key, child] of Object.entries(node)) {
    result[key] = convertNode(child as DtcgNode)
  }
  return result
}

// Matches the quoting style of the hand-written original: plain integers and
// valid identifiers stay bare, everything else (e.g. "4.6", "xlarge-ish") is quoted.
function formatKey(key: string): string {
  if (/^[0-9]+$/.test(key)) return key
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) return key
  return JSON.stringify(key)
}

function serialize(value: unknown, indent: number): string {
  const pad = '  '.repeat(indent)
  const childPad = '  '.repeat(indent + 1)
  if (typeof value === 'string') return `'${value}'`
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
    const body = entries
      .map(([key, val]) => `${childPad}${formatKey(key)}: ${serialize(val, indent + 1)},`)
      .join('\n')
    return `{\n${body}\n${pad}}`
  }
  throw new Error(`Unsupported value: ${JSON.stringify(value)}`)
}

async function main() {
  const source = JSON.parse(readFileSync(SOURCE_PATH, 'utf-8')) as Record<string, DtcgNode>

  const exportBlocks = Object.entries(source)
    .map(([name, group]) => `export const ${name} = ${serialize(convertNode(group), 0)} as const`)
    .join('\n\n')

  const header =
    '// AUTO-GENERATED by scripts/build-tokens.ts from tokens.json — do not edit by hand.\n' +
    '// Source of truth: Figma, synced via Tokens Studio. Edit tokens.json (or Figma) instead.\n\n'

  // No repo-wide .prettierrc exists yet (CLAUDE.md documents singleQuote/semi
  // conventions without a committed config file), so pin them here to match the
  // hand-written style this file replaces.
  const formatted = await prettier.format(header + exportBlocks + '\n', {
    parser: 'typescript',
    singleQuote: true,
    semi: false,
    printWidth: 100,
  })

  writeFileSync(OUTPUT_PATH, formatted)
  console.log(`Wrote ${OUTPUT_PATH}`)
}

main()
