-- =========================================
-- region_cache 시드: 한국관광공사 TourAPI "지역코드조회" 기준
-- 원본: 관광지_시군구_코드정보_v1.0.xlsx (areaCd/areaNm/sigunguCd/sigunguNm, 17개 시/도, 252개 시군구)
-- docs/api-server-boundaries.md, docs/schema-design.md §11 결정사항대로
-- 정적 시드 데이터를 배포 시 1회 삽입 (운영 중 TourAPI 호출로 갱신하지 않음).
--
-- region_code/region_name은 시/도(광역) 단위로 저장한다 — F1 여행 생성 화면의
-- "지역" 입력이 "대구"처럼 시/도 단위 자유텍스트이기 때문. 시군구(구/군) 단위까지
-- region_name으로 저장하면 "중구"처럼 여러 시/도에 동일한 이름이 존재해 자유텍스트
-- 매칭이 모호해진다. 대신 시군구 상세는 tour_api_snapshot(jsonb)에 그대로 보존해서
-- F3(추천, TourAPI 지역기반조회 areaCode+sigunguCode) 쪽에서 나중에 활용할 수 있게 한다.
-- =========================================
insert into public.region_cache (region_code, region_name, tour_api_snapshot)
values
  ('11', '서울특별시', '[{"sigungu_code": "11110", "sigungu_name": "종로구"}, {"sigungu_code": "11140", "sigungu_name": "중구"}, {"sigungu_code": "11170", "sigungu_name": "용산구"}, {"sigungu_code": "11200", "sigungu_name": "성동구"}, {"sigungu_code": "11215", "sigungu_name": "광진구"}, {"sigungu_code": "11230", "sigungu_name": "동대문구"}, {"sigungu_code": "11260", "sigungu_name": "중랑구"}, {"sigungu_code": "11290", "sigungu_name": "성북구"}, {"sigungu_code": "11305", "sigungu_name": "강북구"}, {"sigungu_code": "11320", "sigungu_name": "도봉구"}, {"sigungu_code": "11350", "sigungu_name": "노원구"}, {"sigungu_code": "11380", "sigungu_name": "은평구"}, {"sigungu_code": "11410", "sigungu_name": "서대문구"}, {"sigungu_code": "11440", "sigungu_name": "마포구"}, {"sigungu_code": "11470", "sigungu_name": "양천구"}, {"sigungu_code": "11500", "sigungu_name": "강서구"}, {"sigungu_code": "11530", "sigungu_name": "구로구"}, {"sigungu_code": "11545", "sigungu_name": "금천구"}, {"sigungu_code": "11560", "sigungu_name": "영등포구"}, {"sigungu_code": "11590", "sigungu_name": "동작구"}, {"sigungu_code": "11620", "sigungu_name": "관악구"}, {"sigungu_code": "11650", "sigungu_name": "서초구"}, {"sigungu_code": "11680", "sigungu_name": "강남구"}, {"sigungu_code": "11710", "sigungu_name": "송파구"}, {"sigungu_code": "11740", "sigungu_name": "강동구"}]'::jsonb),
  ('26', '부산광역시', '[{"sigungu_code": "26110", "sigungu_name": "중구"}, {"sigungu_code": "26140", "sigungu_name": "서구"}, {"sigungu_code": "26170", "sigungu_name": "동구"}, {"sigungu_code": "26200", "sigungu_name": "영도구"}, {"sigungu_code": "26230", "sigungu_name": "부산진구"}, {"sigungu_code": "26260", "sigungu_name": "동래구"}, {"sigungu_code": "26290", "sigungu_name": "남구"}, {"sigungu_code": "26320", "sigungu_name": "북구"}, {"sigungu_code": "26350", "sigungu_name": "해운대구"}, {"sigungu_code": "26380", "sigungu_name": "사하구"}, {"sigungu_code": "26410", "sigungu_name": "금정구"}, {"sigungu_code": "26440", "sigungu_name": "강서구"}, {"sigungu_code": "26470", "sigungu_name": "연제구"}, {"sigungu_code": "26500", "sigungu_name": "수영구"}, {"sigungu_code": "26530", "sigungu_name": "사상구"}, {"sigungu_code": "26710", "sigungu_name": "기장군"}]'::jsonb),
  ('27', '대구광역시', '[{"sigungu_code": "27110", "sigungu_name": "중구"}, {"sigungu_code": "27140", "sigungu_name": "동구"}, {"sigungu_code": "27170", "sigungu_name": "서구"}, {"sigungu_code": "27200", "sigungu_name": "남구"}, {"sigungu_code": "27230", "sigungu_name": "북구"}, {"sigungu_code": "27260", "sigungu_name": "수성구"}, {"sigungu_code": "27290", "sigungu_name": "달서구"}, {"sigungu_code": "27710", "sigungu_name": "달성군"}, {"sigungu_code": "27720", "sigungu_name": "군위군"}]'::jsonb),
  ('28', '인천광역시', '[{"sigungu_code": "28110", "sigungu_name": "중구"}, {"sigungu_code": "28140", "sigungu_name": "동구"}, {"sigungu_code": "28177", "sigungu_name": "미추홀구"}, {"sigungu_code": "28185", "sigungu_name": "연수구"}, {"sigungu_code": "28200", "sigungu_name": "남동구"}, {"sigungu_code": "28237", "sigungu_name": "부평구"}, {"sigungu_code": "28245", "sigungu_name": "계양구"}, {"sigungu_code": "28260", "sigungu_name": "서구"}, {"sigungu_code": "28710", "sigungu_name": "강화군"}, {"sigungu_code": "28720", "sigungu_name": "옹진군"}]'::jsonb),
  ('29', '광주광역시', '[{"sigungu_code": "29110", "sigungu_name": "동구"}, {"sigungu_code": "29140", "sigungu_name": "서구"}, {"sigungu_code": "29155", "sigungu_name": "남구"}, {"sigungu_code": "29170", "sigungu_name": "북구"}, {"sigungu_code": "29200", "sigungu_name": "광산구"}]'::jsonb),
  ('30', '대전광역시', '[{"sigungu_code": "30110", "sigungu_name": "동구"}, {"sigungu_code": "30140", "sigungu_name": "중구"}, {"sigungu_code": "30170", "sigungu_name": "서구"}, {"sigungu_code": "30200", "sigungu_name": "유성구"}, {"sigungu_code": "30230", "sigungu_name": "대덕구"}]'::jsonb),
  ('31', '울산광역시', '[{"sigungu_code": "31110", "sigungu_name": "중구"}, {"sigungu_code": "31140", "sigungu_name": "남구"}, {"sigungu_code": "31170", "sigungu_name": "동구"}, {"sigungu_code": "31200", "sigungu_name": "북구"}, {"sigungu_code": "31710", "sigungu_name": "울주군"}]'::jsonb),
  ('36', '세종특별자치시', '[{"sigungu_code": "36110", "sigungu_name": "세종특별자치시"}]'::jsonb),
  ('41', '경기도', '[{"sigungu_code": "41111", "sigungu_name": "수원시 장안구"}, {"sigungu_code": "41113", "sigungu_name": "수원시 권선구"}, {"sigungu_code": "41115", "sigungu_name": "수원시 팔달구"}, {"sigungu_code": "41117", "sigungu_name": "수원시 영통구"}, {"sigungu_code": "41131", "sigungu_name": "성남시 수정구"}, {"sigungu_code": "41133", "sigungu_name": "성남시 중원구"}, {"sigungu_code": "41135", "sigungu_name": "성남시 분당구"}, {"sigungu_code": "41150", "sigungu_name": "의정부시"}, {"sigungu_code": "41171", "sigungu_name": "안양시 만안구"}, {"sigungu_code": "41173", "sigungu_name": "안양시 동안구"}, {"sigungu_code": "41192", "sigungu_name": "부천시 원미구"}, {"sigungu_code": "41194", "sigungu_name": "부천시 소사구"}, {"sigungu_code": "41196", "sigungu_name": "부천시 오정구"}, {"sigungu_code": "41210", "sigungu_name": "광명시"}, {"sigungu_code": "41220", "sigungu_name": "평택시"}, {"sigungu_code": "41250", "sigungu_name": "동두천시"}, {"sigungu_code": "41271", "sigungu_name": "안산시 상록구"}, {"sigungu_code": "41273", "sigungu_name": "안산시 단원구"}, {"sigungu_code": "41281", "sigungu_name": "고양시 덕양구"}, {"sigungu_code": "41285", "sigungu_name": "고양시 일산동구"}, {"sigungu_code": "41287", "sigungu_name": "고양시 일산서구"}, {"sigungu_code": "41290", "sigungu_name": "과천시"}, {"sigungu_code": "41310", "sigungu_name": "구리시"}, {"sigungu_code": "41360", "sigungu_name": "남양주시"}, {"sigungu_code": "41370", "sigungu_name": "오산시"}, {"sigungu_code": "41390", "sigungu_name": "시흥시"}, {"sigungu_code": "41410", "sigungu_name": "군포시"}, {"sigungu_code": "41430", "sigungu_name": "의왕시"}, {"sigungu_code": "41450", "sigungu_name": "하남시"}, {"sigungu_code": "41461", "sigungu_name": "용인시 처인구"}, {"sigungu_code": "41463", "sigungu_name": "용인시 기흥구"}, {"sigungu_code": "41465", "sigungu_name": "용인시 수지구"}, {"sigungu_code": "41480", "sigungu_name": "파주시"}, {"sigungu_code": "41500", "sigungu_name": "이천시"}, {"sigungu_code": "41550", "sigungu_name": "안성시"}, {"sigungu_code": "41570", "sigungu_name": "김포시"}, {"sigungu_code": "41590", "sigungu_name": "화성시"}, {"sigungu_code": "41610", "sigungu_name": "광주시"}, {"sigungu_code": "41630", "sigungu_name": "양주시"}, {"sigungu_code": "41650", "sigungu_name": "포천시"}, {"sigungu_code": "41670", "sigungu_name": "여주시"}, {"sigungu_code": "41800", "sigungu_name": "연천군"}, {"sigungu_code": "41820", "sigungu_name": "가평군"}, {"sigungu_code": "41830", "sigungu_name": "양평군"}]'::jsonb),
  ('43', '충청북도', '[{"sigungu_code": "43111", "sigungu_name": "청주시 상당구"}, {"sigungu_code": "43112", "sigungu_name": "청주시 서원구"}, {"sigungu_code": "43113", "sigungu_name": "청주시 흥덕구"}, {"sigungu_code": "43114", "sigungu_name": "청주시 청원구"}, {"sigungu_code": "43130", "sigungu_name": "충주시"}, {"sigungu_code": "43150", "sigungu_name": "제천시"}, {"sigungu_code": "43720", "sigungu_name": "보은군"}, {"sigungu_code": "43730", "sigungu_name": "옥천군"}, {"sigungu_code": "43740", "sigungu_name": "영동군"}, {"sigungu_code": "43745", "sigungu_name": "증평군"}, {"sigungu_code": "43750", "sigungu_name": "진천군"}, {"sigungu_code": "43760", "sigungu_name": "괴산군"}, {"sigungu_code": "43770", "sigungu_name": "음성군"}, {"sigungu_code": "43800", "sigungu_name": "단양군"}]'::jsonb),
  ('44', '충청남도', '[{"sigungu_code": "44131", "sigungu_name": "천안시 동남구"}, {"sigungu_code": "44133", "sigungu_name": "천안시 서북구"}, {"sigungu_code": "44150", "sigungu_name": "공주시"}, {"sigungu_code": "44180", "sigungu_name": "보령시"}, {"sigungu_code": "44200", "sigungu_name": "아산시"}, {"sigungu_code": "44210", "sigungu_name": "서산시"}, {"sigungu_code": "44230", "sigungu_name": "논산시"}, {"sigungu_code": "44250", "sigungu_name": "계룡시"}, {"sigungu_code": "44270", "sigungu_name": "당진시"}, {"sigungu_code": "44710", "sigungu_name": "금산군"}, {"sigungu_code": "44760", "sigungu_name": "부여군"}, {"sigungu_code": "44770", "sigungu_name": "서천군"}, {"sigungu_code": "44790", "sigungu_name": "청양군"}, {"sigungu_code": "44800", "sigungu_name": "홍성군"}, {"sigungu_code": "44810", "sigungu_name": "예산군"}, {"sigungu_code": "44825", "sigungu_name": "태안군"}]'::jsonb),
  ('46', '전라남도', '[{"sigungu_code": "46110", "sigungu_name": "목포시"}, {"sigungu_code": "46130", "sigungu_name": "여수시"}, {"sigungu_code": "46150", "sigungu_name": "순천시"}, {"sigungu_code": "46170", "sigungu_name": "나주시"}, {"sigungu_code": "46230", "sigungu_name": "광양시"}, {"sigungu_code": "46710", "sigungu_name": "담양군"}, {"sigungu_code": "46720", "sigungu_name": "곡성군"}, {"sigungu_code": "46730", "sigungu_name": "구례군"}, {"sigungu_code": "46770", "sigungu_name": "고흥군"}, {"sigungu_code": "46780", "sigungu_name": "보성군"}, {"sigungu_code": "46790", "sigungu_name": "화순군"}, {"sigungu_code": "46800", "sigungu_name": "장흥군"}, {"sigungu_code": "46810", "sigungu_name": "강진군"}, {"sigungu_code": "46820", "sigungu_name": "해남군"}, {"sigungu_code": "46830", "sigungu_name": "영암군"}, {"sigungu_code": "46840", "sigungu_name": "무안군"}, {"sigungu_code": "46860", "sigungu_name": "함평군"}, {"sigungu_code": "46870", "sigungu_name": "영광군"}, {"sigungu_code": "46880", "sigungu_name": "장성군"}, {"sigungu_code": "46890", "sigungu_name": "완도군"}, {"sigungu_code": "46900", "sigungu_name": "진도군"}, {"sigungu_code": "46910", "sigungu_name": "신안군"}]'::jsonb),
  ('47', '경상북도', '[{"sigungu_code": "47111", "sigungu_name": "포항시 남구"}, {"sigungu_code": "47113", "sigungu_name": "포항시 북구"}, {"sigungu_code": "47130", "sigungu_name": "경주시"}, {"sigungu_code": "47150", "sigungu_name": "김천시"}, {"sigungu_code": "47170", "sigungu_name": "안동시"}, {"sigungu_code": "47190", "sigungu_name": "구미시"}, {"sigungu_code": "47210", "sigungu_name": "영주시"}, {"sigungu_code": "47230", "sigungu_name": "영천시"}, {"sigungu_code": "47250", "sigungu_name": "상주시"}, {"sigungu_code": "47280", "sigungu_name": "문경시"}, {"sigungu_code": "47290", "sigungu_name": "경산시"}, {"sigungu_code": "47730", "sigungu_name": "의성군"}, {"sigungu_code": "47750", "sigungu_name": "청송군"}, {"sigungu_code": "47760", "sigungu_name": "영양군"}, {"sigungu_code": "47770", "sigungu_name": "영덕군"}, {"sigungu_code": "47820", "sigungu_name": "청도군"}, {"sigungu_code": "47830", "sigungu_name": "고령군"}, {"sigungu_code": "47840", "sigungu_name": "성주군"}, {"sigungu_code": "47850", "sigungu_name": "칠곡군"}, {"sigungu_code": "47900", "sigungu_name": "예천군"}, {"sigungu_code": "47920", "sigungu_name": "봉화군"}, {"sigungu_code": "47930", "sigungu_name": "울진군"}, {"sigungu_code": "47940", "sigungu_name": "울릉군"}]'::jsonb),
  ('48', '경상남도', '[{"sigungu_code": "48121", "sigungu_name": "창원시 의창구"}, {"sigungu_code": "48123", "sigungu_name": "창원시 성산구"}, {"sigungu_code": "48125", "sigungu_name": "창원시 마산합포구"}, {"sigungu_code": "48127", "sigungu_name": "창원시 마산회원구"}, {"sigungu_code": "48129", "sigungu_name": "창원시 진해구"}, {"sigungu_code": "48170", "sigungu_name": "진주시"}, {"sigungu_code": "48220", "sigungu_name": "통영시"}, {"sigungu_code": "48240", "sigungu_name": "사천시"}, {"sigungu_code": "48250", "sigungu_name": "김해시"}, {"sigungu_code": "48270", "sigungu_name": "밀양시"}, {"sigungu_code": "48310", "sigungu_name": "거제시"}, {"sigungu_code": "48330", "sigungu_name": "양산시"}, {"sigungu_code": "48720", "sigungu_name": "의령군"}, {"sigungu_code": "48730", "sigungu_name": "함안군"}, {"sigungu_code": "48740", "sigungu_name": "창녕군"}, {"sigungu_code": "48820", "sigungu_name": "고성군"}, {"sigungu_code": "48840", "sigungu_name": "남해군"}, {"sigungu_code": "48850", "sigungu_name": "하동군"}, {"sigungu_code": "48860", "sigungu_name": "산청군"}, {"sigungu_code": "48870", "sigungu_name": "함양군"}, {"sigungu_code": "48880", "sigungu_name": "거창군"}, {"sigungu_code": "48890", "sigungu_name": "합천군"}]'::jsonb),
  ('50', '제주특별자치도', '[{"sigungu_code": "50110", "sigungu_name": "제주시"}, {"sigungu_code": "50130", "sigungu_name": "서귀포시"}]'::jsonb),
  ('51', '강원특별자치도', '[{"sigungu_code": "51110", "sigungu_name": "춘천시"}, {"sigungu_code": "51130", "sigungu_name": "원주시"}, {"sigungu_code": "51150", "sigungu_name": "강릉시"}, {"sigungu_code": "51170", "sigungu_name": "동해시"}, {"sigungu_code": "51190", "sigungu_name": "태백시"}, {"sigungu_code": "51210", "sigungu_name": "속초시"}, {"sigungu_code": "51230", "sigungu_name": "삼척시"}, {"sigungu_code": "51720", "sigungu_name": "홍천군"}, {"sigungu_code": "51730", "sigungu_name": "횡성군"}, {"sigungu_code": "51750", "sigungu_name": "영월군"}, {"sigungu_code": "51760", "sigungu_name": "평창군"}, {"sigungu_code": "51770", "sigungu_name": "정선군"}, {"sigungu_code": "51780", "sigungu_name": "철원군"}, {"sigungu_code": "51790", "sigungu_name": "화천군"}, {"sigungu_code": "51800", "sigungu_name": "양구군"}, {"sigungu_code": "51810", "sigungu_name": "인제군"}, {"sigungu_code": "51820", "sigungu_name": "고성군"}, {"sigungu_code": "51830", "sigungu_name": "양양군"}]'::jsonb),
  ('52', '전북특별자치도', '[{"sigungu_code": "52111", "sigungu_name": "전주시 완산구"}, {"sigungu_code": "52113", "sigungu_name": "전주시 덕진구"}, {"sigungu_code": "52130", "sigungu_name": "군산시"}, {"sigungu_code": "52140", "sigungu_name": "익산시"}, {"sigungu_code": "52180", "sigungu_name": "정읍시"}, {"sigungu_code": "52190", "sigungu_name": "남원시"}, {"sigungu_code": "52210", "sigungu_name": "김제시"}, {"sigungu_code": "52710", "sigungu_name": "완주군"}, {"sigungu_code": "52720", "sigungu_name": "진안군"}, {"sigungu_code": "52730", "sigungu_name": "무주군"}, {"sigungu_code": "52740", "sigungu_name": "장수군"}, {"sigungu_code": "52750", "sigungu_name": "임실군"}, {"sigungu_code": "52770", "sigungu_name": "순창군"}, {"sigungu_code": "52790", "sigungu_name": "고창군"}, {"sigungu_code": "52800", "sigungu_name": "부안군"}]'::jsonb)
on conflict (region_code) do update
  set region_name = excluded.region_name,
      tour_api_snapshot = excluded.tour_api_snapshot;
